export const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000/api';
export const WS_URL = import.meta.env.VITE_WS_URL || 'ws://localhost:8080';

export const TASK_STATUS = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  REVIEW: 'REVIEW',
  DONE: 'DONE'
};

export const USER_ROLE = {
  LEADER: 'LEADER',
  MEMBER: 'MEMBER'
};

export const WS_EVENTS = {
  AUTHENTICATE: 'AUTHENTICATE',
  JOIN_PROJECT: 'JOIN_PROJECT',
  LEAVE_PROJECT: 'LEAVE_PROJECT',
  CREATE_TASK: 'CREATE_TASK',
  UPDATE_TASK_STATUS: 'UPDATE_TASK_STATUS',
  ASSIGN_TASK: 'ASSIGN_TASK',
  ADD_COMMENT: 'ADD_COMMENT',
  START_VIEWING_TASK: 'START_VIEWING_TASK',
  STOP_VIEWING_TASK: 'STOP_VIEWING_TASK',
  START_EDITING_TASK: 'START_EDITING_TASK',
  STOP_EDITING_TASK: 'STOP_EDITING_TASK',
  CONNECTION_ESTABLISHED: 'CONNECTION_ESTABLISHED',
  AUTHENTICATED: 'AUTHENTICATED',
  AUTH_ERROR: 'AUTH_ERROR',
  PROJECT_JOINED: 'PROJECT_JOINED',
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_STATUS_UPDATED: 'TASK_STATUS_UPDATED',
  TASK_COMMENT_ADDED: 'TASK_COMMENT_ADDED',
  TASK_VIEWER_JOINED: 'TASK_VIEWER_JOINED',
  TASK_VIEWER_LEFT: 'TASK_VIEWER_LEFT',
  TASK_EDITOR_JOINED: 'TASK_EDITOR_JOINED',
  TASK_EDITOR_LEFT: 'TASK_EDITOR_LEFT',
  ERROR: 'ERROR'
};
